services:
  blockchain:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blockchain
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

volumes:
  redis_data:

